### ISSUE TITLE
Feature Request-RSS Feed

### ISSUE THREAD

**Issue by silverly** [ManchesterGreyHats/ManchesterGreyHatsBlog-Hugo#10]
Hi There!

Im wondering if you can modify the theme to add the rss feed so we can follow you blog :)

**Comment by jahmelharris** [comment]
It's already there :)

https://blog.manchestergreyhats.co.uk/posts/index.xml

**Comment by silverly** [comment]
Thank you, i was looking forever it! Your blog is excellent btw.

**Comment by jahmelharris** [comment]
Thanks a lot :) If you ever want to post an article, feel free to submit a pull request! We'd like this to be a community blog open to anyone.
